### ISSUE TITLE
Migrating to effector v22 causes errors

### ISSUE THREAD

**Issue by uulaal** [yumauri/effector-reeffect#24]

**Comment by yumauri** [comment]
Yes, current version is not compatible with effector v22 :(
Unfortunately I cannot tell ETA for new version, but PR are welcome!

**Comment by binjospookie** [comment]
What should we do to support v22?

**Comment by yumauri** [comment]
https://github.com/yumauri/effector-reeffect/issues/26

**Comment by yumauri** [comment]
Release [v3.0.0](https://github.com/yumauri/effector-reeffect/releases/tag/v3.0.0) was landed, it is compatible with effector v22, and even `fork` should work with this version.

You can check it out, alas, due to #26, I suggest you to remove `effector-reeffect` from your codebase as soon as possible.

Thank you for being this package users, but we need to go further.
